# CIRCUITPYTHON configurations
CIRCUITPY_BLE_NAME="PECKUS"


# PECKUS core options
PECKUS_CONFIG_FILENAME="/peckus.json"
PECKUS_PAYLOAD_FILENAME="/secret.txt"
# PECKUS workflow-specific parameters: /peckus.json (CIRCUITPY/peckus.json in this repository)
PECKUS_BLE_PRESENCE="TRUE"
PECKUS_BLE_PRESENCE_GRACE_SECS=15
PECKUS_RELOCK_SECS=0


# PECKUS security related configuration variables
PECKUS_USB_CONSOLE="TRUE"
PECKUS_BLE_CONSOLE="TRUE"


# PECKUS debugging (or for evaluation purposes) configuration options
PECKUS_DEBUG="TRUE"
PECKUS_DEBUG_BOOTPY_FACTORYRESET_ON_POWERON="TRUE"
PECKUS_DEBUG_CODEPY_WAIT4CONSOLE="TRUE"
PECKUS_DEBUG_CODEPY_WAIT4SECONDS=0

