# CIRCUITPYTHON configurations
CIRCUITPY_BLE_NAME="PECKUS"


# PECKUS core options
PECKUS_CONFIG_FILENAME="/conf.d/demo-btn+ble.json"
PECKUS_PAYLOAD_FILENAME="/secret.txt"
# PECKUS configuration-specific parameters: /conf.d/demo-btn.json
PECKUS_RELOCK_TIMEOUT_SECS=60
# PECKUS configuration-specific parameters: /conf.d/demo-btn+ble.json
PECKUS_RELOCK_BLE_RECONNECT_GRACE_SECS=15


# PECKUS security related configuration variables
PECKUS_USB_CONSOLE="TRUE"
PECKUS_BLE_CONSOLE="TRUE"


# PECKUS debugging (or for evaluation purposes) configuration options
PECKUS_DEBUG="TRUE"
PECKUS_DEBUG_BOOTPY_FACTORYRESET_ON_POWERON="TRUE"
PECKUS_DEBUG_CODEPY_WAIT4SECONDS=0
PECKUS_DEBUG_CODEPY_WAIT4CONSOLE="FALSE"

