# PECKUS core configuration
PECKUS_CONFIG_FILENAME="peckus.json"
PECKUS_PAYLOAD_FILENAME="secret.txt"


# PECKUS workflow-specific parameters: ./peckus.json (-> conf.d/default.json)
PECKUS_UNLOCK_PRESENCE_BTN="TRUE"
PECKUS_UNLOCK_PRESENCE_BLE="TRUE"
PECKUS_UNLOCK_PRESENCE_BLE_GRACE_SECS="15"
PECKUS_RELOCK_SECS="0"


PECKUS_DEVICE_USB_VENDOR="CIRCUITPYTHON"
PECKUS_DEVICE_USB_PRODUCT="PECKUS"
PECKUS_DEVICE_USB_VID="239a"
PECKUS_DEVICE_USB_PID="2025"
PECKUS_DEVICE_BLE_NAME="PECKUS"


# PECKUS hardening related configuration variables
PECKUS_CONSOLE_USB="TRUE"
PECKUS_FILESYSTEM_KEEP_CONFIG_JSON="TRUE"
PECKUS_FILESYSTEM_KEEP_SETTINGS_TOML="TRUE"


# PECKUS debugging (or for evaluation purposes) configuration options
PECKUS_DEBUG="TRUE"
PECKUS_DEBUG_BOOTPY_FACTORYRESET_ON_POWERON="TRUE"
PECKUS_DEBUG_CODEPY_WAIT4CONSOLE="FALSE"
PECKUS_DEBUG_CODEPY_WAIT4SECONDS="0"

