## DEBUG configuration: 
## - (only) button-push required for unlocking
## - 60sec relocking timout
## - USB CDC serial (console/REPL) is enabled
## - boot.py performs a factory-reset upon power-on (whenever the device is plugged in), this should be as if PECKUS was just freshly installed
## - code.py will wait for an USB console/REPL connection before running any application logic

# application configuration
PECKUS_APP_CONFIG_FILENAME="peckus.json"
PECKUS_APP_PAYLOAD_FILENAME="secret.txt"

# workflow-specific parameters: ./peckus.json (-> conf.d/peckus.json.d/default.json)
PECKUS_UNLOCK_PRESENCE_BTN="TRUE"
PECKUS_UNLOCK_PRESENCE_BTN_VALIDITY_SECS="60"
PECKUS_UNLOCK_PRESENCE_BLE="FALSE"
PECKUS_UNLOCK_PRESENCE_BLE_VALIDITY_SECS="0"
PECKUS_RELOCK_TIMEOUT="TRUE"
PECKUS_RELOCK_TIMEOUT_SECS="60"
PECKUS_RELOCK_PRESENCE_BLE="FALSE"
PECKUS_RELOCK_PRESENCE_BLE_GRACE_SECS="0"

# device identification
PECKUS_DEVICE_USB_VENDOR="CIRCUITPYTHON"
PECKUS_DEVICE_USB_PRODUCT="PECKUS"
PECKUS_DEVICE_USB_VID="239a"
PECKUS_DEVICE_USB_PID="2025"
PECKUS_DEVICE_BLE_NAME="PECKUS"

# security related configuration variables
PECKUS_CONSOLE_USB="TRUE"

# debugging (or for evaluation purposes) configuration options
PECKUS_DEBUG="TRUE"
PECKUS_DEBUG_BOOTPY_FACTORYRESET_ON_POWERON="TRUE"
PECKUS_DEBUG_CODEPY_WAIT4CONSOLE="TRUE"

