## DEMO configuration: 
## - button-push and BLE connection for unlocking
## - 5min timout for automatic relocking, or if BLE connection is lost for 15secs
## - USB CDC serial (console/REPL) is enabled - this might be your saving life-line during testing

# application configuration
PECKUS_APP_CONFIG_FILENAME="peckus.json"
PECKUS_APP_PAYLOAD_FILENAME="secret.txt"

# workflow-specific parameters: ./peckus.json (-> conf.d/peckus.json.d/default.json)
PECKUS_UNLOCK_PRESENCE_BTN="TRUE"
PECKUS_UNLOCK_PRESENCE_BTN_VALIDITY_SECS="30"
PECKUS_UNLOCK_PRESENCE_BLE="TRUE"
PECKUS_UNLOCK_PRESENCE_BLE_VALIDITY_SECS="30"
PECKUS_RELOCK_TIMEOUT="TRUE"
PECKUS_RELOCK_TIMEOUT_SECS="300"
PECKUS_RELOCK_PRESENCE_BLE="TRUE"
PECKUS_RELOCK_PRESENCE_BLE_GRACE_SECS="15"

# device identification
PECKUS_DEVICE_USB_VENDOR="CIRCUITPYTHON"
PECKUS_DEVICE_USB_PRODUCT="PECKUS"
PECKUS_DEVICE_USB_VID="239a"
PECKUS_DEVICE_USB_PID="2025"
PECKUS_DEVICE_BLE_NAME="PECKUS"

# security related configuration variables
PECKUS_CONSOLE_USB="TRUE"

# debugging (or for evaluation purposes) configuration options
PECKUS_DEBUG="FALSE"
PECKUS_DEBUG_BOOTPY_FACTORYRESET_ON_POWERON="FALSE"
PECKUS_DEBUG_CODEPY_WAIT4CONSOLE="FALSE"

